name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Spotless check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.0
      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: adopt
          java-version: 17
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: spotless
        run: ./gradlew spotlessCheck

  detekt:
    name: Detekt check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.0
      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: adopt
          java-version: 17
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: detekt
        run: ./gradlew detekt

  build:
    name: Build, Tests, Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew app:koverXmlReportDebug

      - name: Upload reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./build/reports/kover
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

